name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  rspec:
    uses: ./.github/workflows/rspec.yml
  rubocop:
    uses: ./.github/workflows/rubocop.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [rspec, rubocop]
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
          github_token: ${{ secrets.GITHUB_TOKEN }}