name: RuboCop

on:
  workflow_call: null
  push:
    branches:
      - '*'
      - '!main'

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          gem install --default -v0.6.0 error_highlight

      - name: Run RuboCop
        run: bundle exec rubocop
